name: learn-github-actions
on:
  schedule:
  - cron:  '35 15 * * *'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: action-slack
        uses: 8398a7/action-slack@v3.12.0
        with:
          status: ${{ job.status }}
          author_name: Integration Test # default: 8398a7@action-slack
          fields: repo,commit,message,author # default: repo,commit
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
        if: always() # Pick up events even if the job fails or is canceled.
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
