on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 15 * * *'
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.https://hooks.slack.com/services/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 }}
