name: slack-notify
on:
  schedule:
  - cron:  '35 15 * * *'
  workflow_dispatch:
  
jobs:
  notify-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: slackapi/slack-github-action@v1.17.0
      - name: slack test
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        run: echo at the end
